import { createAction } from 'redux-actions'

export const FETCH_SERVICE = 'FETCH_SERVICE'
const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST'
const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS'
const FETCH_SERVICE_ERROR = 'FETCH_SERVICE_ERROR'

export const FETCH_SAMPLE_SERVICE = 'FETCH_SAMPLE_SERVICE'
const FETCH_SAMPLE_SERVICE_REQUEST = 'FETCH_SAMPLE_SERVICE_REQUEST'
const FETCH_SAMPLE_SERVICE_SUCCESS = 'FETCH_SAMPLE_SERVICE_SUCCESS'
const FETCH_SAMPLE_SERVICE_ERROR = 'FETCH_SAMPLE_SERVICE_ERROR'

export const ADD_SERVICE_FROM_SAMPLE_SERVICE = 'ADD_SERVICE_FROM_SAMPLE_SERVICE'
const ADD_SERVICE_FROM_SAMPLE_SERVICE_REQUEST = 'ADD_SERVICE_FROM_SAMPLE_SERVICE_REQUEST'
const ADD_SERVICE_FROM_SAMPLE_SERVICE_SUCCESS = 'ADD_SERVICE_FROM_SAMPLE_SERVICE_SUCCESS'
const ADD_SERVICE_FROM_SAMPLE_SERVICE_ERROR = 'ADD_SERVICE_FROM_SAMPLE_SERVICE_ERROR'

export const FETCH_SAMPLE_YOUR_SERVICE = 'FETCH_SAMPLE_YOUR_SERVICE'
const FETCH_SAMPLE_YOUR_SERVICE_REQUEST = 'FETCH_SAMPLE_YOUR_SERVICE_REQUEST'
const FETCH_SAMPLE_YOUR_SERVICE_SUCCESS = 'FETCH_SAMPLE_YOUR_SERVICE_SUCCESS'
const FETCH_SAMPLE_YOUR_SERVICE_ERROR = 'FETCH_SAMPLE_YOUR_SERVICE_ERROR'

export const ADD_YOUR_SERVICE = 'ADD_YOUR_SERVICE'
const ADD_YOUR_SERVICE_REQUEST = 'ADD_YOUR_SERVICE_REQUEST'
const ADD_YOUR_SERVICE_SUCCESS = 'ADD_YOUR_SERVICE_SUCCESS'
const ADD_YOUR_SERVICE_ERROR = 'ADD_YOUR_SERVICE_ERROR'


export const fetchServiceRequest = createAction(FETCH_SERVICE_REQUEST)
export const fetchServiceSuccess = createAction(FETCH_SERVICE_SUCCESS)
export const fetchServiceError = createAction(FETCH_SERVICE_ERROR)

export const fetchSampleServiceRequest = createAction(FETCH_SAMPLE_SERVICE_REQUEST)
export const fetchSampleServiceSuccess = createAction(FETCH_SAMPLE_SERVICE_SUCCESS)
export const fetchSampleServiceError = createAction(FETCH_SAMPLE_SERVICE_ERROR)

export const addServiceFromSampleServiceRequest = createAction(ADD_SERVICE_FROM_SAMPLE_SERVICE_REQUEST)
export const addServiceFromSampleServiceSuccess = createAction(ADD_SERVICE_FROM_SAMPLE_SERVICE_SUCCESS)
export const addServiceFromSampleServiceError = createAction(ADD_SERVICE_FROM_SAMPLE_SERVICE_ERROR)

export const fetchSampleYourServiceRequest = createAction(FETCH_SAMPLE_YOUR_SERVICE_REQUEST)
export const fetchSampleYourServiceSuccess = createAction(FETCH_SAMPLE_YOUR_SERVICE_SUCCESS)
export const fetchSampleYourServiceError = createAction(FETCH_SAMPLE_YOUR_SERVICE_ERROR)

export const addYourServiceRequest = createAction(ADD_YOUR_SERVICE_REQUEST)
export const addYourServiceSuccess = createAction(ADD_YOUR_SERVICE_SUCCESS)
export const addYourServiceError = createAction(ADD_YOUR_SERVICE_ERROR)